######################################################################
# Automatically generated by qmake (3.0) Wed Nov 11 22:23:47 2015
######################################################################

TEMPLATE = app
TARGET = sokoban_solverv1
INCLUDEPATH += .
CONFIG +=c++11
# Directories

# Input
HEADERS += sokoban.h
SOURCES += sokoban.cpp main.cpp
